#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

[build]
    base = "packages/app/"
    publish = "public/"
    command = "yarn build"
    ignore = "git diff --quiet master ."
