#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

[build]
    base = "packages/contentful-extensions/"
    publish = "build/"
    command = "yarn build"
    ignore = "git diff --quiet master ."
